(() => {
 const $=id=>document.getElementById(id); const api=async(path,body={})=>{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||'Request failed');return j};
 const DEFAULT={key:'pre-registration',serial:'01',title:'PRE-REGISTRATION',subtitle:'MASTER REGISTRATION',fee:200,qr:'assets/payment/pre-registration.png',note:'Pay ₹200 using the QR code and enter the UTR.',description:'Pre-registration is compulsory. Your registered mobile number becomes your participant login password.',fields:[],team:false,enabled:true};
 let portal={...DEFAULT},draft={};
 const identity=$('identityGate'),choices=$('identityGrid'),intro=$('identityIntro'),payment=$('paymentGate'),formShell=$('portalShell'),form=$('registrationForm'),creation=$('creationOverlay'),creationStatus=$('creationStatus');
 const email=$('email'),mobile=$('mobile'),formStatus=$('formStatus'),gateStatus=$('gateStatus');
 const save=()=>{const fd=new FormData(form);draft={name:String(fd.get('fullName')||'').trim(),email:String(email.value||'').trim().toLowerCase(),phone:String(mobile.value||'').replace(/\D/g,''),year:String(fd.get('year')||'')};sessionStorage.setItem('exc_pre_draft',JSON.stringify(draft));};
 try{draft=JSON.parse(sessionStorage.getItem('exc_pre_draft')||'{}')}catch{}
 function details(){identity.hidden=true;payment.hidden=true;formShell.hidden=false;$('portalSerial').textContent=portal.serial;$('portalTitle').textContent=portal.title;$('portalSubtitle').textContent=portal.subtitle;$('portalDescription').textContent=portal.description||'';}
 $('startPreRegistration')?.addEventListener('click',()=>{details();$('fullName')?.focus()});
 mobile?.addEventListener('input',()=>{mobile.value=mobile.value.replace(/\D/g,'').slice(0,10);save()}); email?.addEventListener('input',save);
 $('registrationForm')?.addEventListener('submit',e=>{e.preventDefault();formStatus.textContent='';const name=form.querySelector('[name="fullName"]').value.trim(),year=form.querySelector('[name="year"]').value;if(name.length<2||!year||!/^\S+@gmail\.com$/i.test(email.value)||!/^[0-9]{10}$/.test(mobile.value))return formStatus.textContent='Complete your name, Gmail, mobile number and year.';save();payment.hidden=false;formShell.hidden=true;const fee=Number(portal.fee||200);$('gateAmount').textContent='₹'+fee.toLocaleString('en-IN');$('gateNote').textContent=portal.note||'';const img=new Image();img.alt='Payment QR';img.src=portal.qr||'';img.onload=()=>{$('gateQr').replaceChildren(img)};img.onerror=()=>{$('gateQr').textContent='QR NOT AVAILABLE'};});
 $('backToTypes')?.addEventListener('click',()=>{payment.hidden=true;formShell.hidden=false});
 $('continueToPortal')?.addEventListener('click',async()=>{if(!$('gatePaid').checked)return gateStatus.textContent='CONFIRM PAYMENT FIRST';const utr=$('gateUtr').value.trim();if(!utr)return gateStatus.textContent='ENTER UTR / TRANSACTION NUMBER';$('continueToPortal').disabled=true;gateStatus.textContent='';creation.hidden=false;document.body.classList.add('creation-active');let t=0;const timer=setInterval(()=>{t++;if(t===2&&creationStatus)creationStatus.textContent='SECURING REGISTRATION DETAILS…';if(t===4&&creationStatus)creationStatus.textContent='GENERATING UNIQUE MASTER ID…';if(t===7&&creationStatus)creationStatus.textContent='FINALISING YOUR REGISTRATION…'},1000);try{const r=await api('register-master',{name:draft.name,email:draft.email,phone:'+91'+draft.phone,year:draft.year,utr});clearInterval(timer);if(creationStatus)creationStatus.textContent='MASTER ID CREATED • READY';$('registrationId').textContent=r.masterId||''; const successName=$('successName'); if(successName)successName.textContent=draft.name||'';localStorage.setItem('exc_portal_access',JSON.stringify({accessToken:r.accessToken,master:{masterId:r.masterId,name:draft.name,email:draft.email,phone:'+91'+draft.phone,preRegistered:true,year:draft.year},expiresAt:Number(r.sessionExpiresAt||Date.now()+Number(r.sessionMinutes||30)*60*1000)}));sessionStorage.removeItem('exc_pre_draft');setTimeout(()=>{creation.hidden=true;document.body.classList.remove('creation-active');$('successOverlay').hidden=false},500)}catch(e){clearInterval(timer);creation.hidden=true;document.body.classList.remove('creation-active');gateStatus.textContent=e.message;$('continueToPortal').disabled=false}});
 $('closeSuccess')?.addEventListener('click',()=>{ window.location.href='registration-portals.html'; });
 const jarvisBtn=$('jarvisBtn'),jarvisPanel=$('jarvisPanel'),jarvisClose=$('jarvisClose');
 if(jarvisBtn&&jarvisPanel){jarvisBtn.addEventListener('click',()=>{jarvisPanel.classList.add('open');jarvisPanel.setAttribute('aria-hidden','false')});jarvisClose?.addEventListener('click',()=>{jarvisPanel.classList.remove('open');jarvisPanel.setAttribute('aria-hidden','true')});jarvisPanel.addEventListener('click',e=>{if(e.target===jarvisPanel)jarvisClose?.click()});const routes={HOME:'site.html',REGISTRATIONS:'registration-portals.html',PROFILE:'profile-verification.html','GENERAL RULES':'general-rules.html',CONTACTS:'contact.html'};document.querySelectorAll('.jarvis-links button').forEach(b=>b.addEventListener('click',()=>{if(routes[b.dataset.target])location.href=routes[b.dataset.target]}));}
 fetch('/api/public-registration-state',{method:'POST'}).then(r=>r.json()).then(j=>{const p=(j.events||[]).find(x=>x.key==='pre-registration');if(p)portal={...portal,...p};}).catch(()=>{});
})();
